# Generated by Django 4.2.5 on 2023-10-02 20:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_no', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name_de', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name_fr', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name_it', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_ubiquitous', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin_url', models.URLField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_in_recipe', models.CharField(max_length=64)),
                ('is_optional', models.BooleanField(default=False)),
                ('group_name', models.CharField(blank=True, max_length=128)),
                ('base_amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('measurement', models.CharField(blank=True, choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('l', 'Liters'), ('dl', 'Deciliters'), ('cl', 'Centiliters'), ('ml', 'Milliliters'), ('tbsp', 'Tablespoons'), ('tsp', 'Teaspoons'), ('', 'Count'), ('slices', 'Slices')], max_length=16)),
                ('base_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe')),
            ],
        ),
    ]
