# Generated by Django 4.2.5 on 2023-10-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='amount_per_serving',
            new_name='base_amount',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('l', 'Liters'), ('dl', 'Deciliters'), ('cl', 'Centiliters'), ('ml', 'Milliliters'), ('tbsp', 'Tablespoons'), ('tsp', 'Teaspoons'), ('', 'Count'), ('slices', 'Slices')], max_length=16),
        ),
    ]
