# Generated by Django 4.2.5 on 2023-10-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_amount_per_serving_recipeingredient_base_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='group_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
