# Generated by Django 4.2.5 on 2023-10-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_servings_alter_recipe_total_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingress',
            new_name='preamble',
        ),
    ]
