# Generated by Django 4.2.5 on 2023-10-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipeingredient_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('oz', 'Ounce'), ('lb', 'Pound'), ('l', 'Liter'), ('dl', 'Deciliter'), ('cl', 'Centiliter'), ('ml', 'Milliliter'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('count', 'Count'), ('slice', 'Slice'), ('cm', 'Centimetre'), ('inch', 'Inch')], max_length=16),
        ),
    ]
