# Generated by Django 4.2.5 on 2023-10-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipeingredient_base_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='recipes/hero_images'),
        ),
    ]
