# Generated by Django 4.2.5 on 2023-10-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_language_recipe_original_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='servings',
            new_name='yields_number',
        ),
        migrations.AddField(
            model_name='recipe',
            name='yields_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('oz', 'Ounce'), ('lb', 'Pound'), ('l', 'Liter'), ('dl', 'Deciliter'), ('cl', 'Centiliter'), ('ml', 'Milliliter'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('count', 'Count'), ('slice', 'Slice'), ('cm', 'Centimetre'), ('inch', 'Inch'), ('', 'Blank')], max_length=16),
        ),
    ]
