# Generated by Django 4.2.5 on 2023-10-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_servings_recipe_yields_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='language',
            field=models.CharField(blank=True, choices=[('no', 'Norwegian'), ('en', 'English'), ('de', 'German'), ('fr', 'French'), ('it', 'Italian')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='original_author',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='other_source',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preamble',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yields_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('oz', 'Ounce'), ('lb', 'Pound'), ('l', 'Liter'), ('dl', 'Deciliter'), ('cl', 'Centiliter'), ('ml', 'Milliliter'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('count', 'Count'), ('slice', 'Slice'), ('cm', 'Centimetre'), ('inch', 'Inch'), ('', 'Blank')], default='', max_length=16),
        ),
    ]
