# Generated by Django 4.2.5 on 2023-10-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='recipes/hero_images'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('oz', 'Ounce'), ('lb', 'Pound'), ('l', 'Liter'), ('dl', 'Deciliter'), ('cl', 'Centiliter'), ('ml', 'Milliliter'), ('cup', 'Cup'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('count', 'Count'), ('slice', 'Slice'), ('cm', 'Centimetre'), ('inch', 'Inch'), ('', 'Blank')], default='', max_length=16),
        ),
    ]
