# Generated by Django 5.0.3 on 2024-03-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_rename_content_recipe_rest_text_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='language',
            field=models.CharField(blank=True, choices=[('no', 'Norwegian'), ('en', 'English'), ('de', 'German'), ('fr', 'French'), ('it', 'Italian')], default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='original_author',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preamble',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rest_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='group_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('title__exact', ''), _negated=True), name='title not empty'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('preamble__exact', ''), _negated=True), name='preamble not empty'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('instructions__exact', ''), _negated=True), name='instructions not empty'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('rest_text__exact', ''), _negated=True), name='rest_text not empty'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('original_author__exact', ''), _negated=True), name='original_author not empty'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(check=models.Q(('group_name__exact', ''), _negated=True), name='group_name not empty'),
        ),
    ]
