# Generated by Django 5.0.3 on 2024-04-01 10:52

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_recipe_instructions_alter_recipe_language_and_more'),
    ]

    operations = [
        # Equivalent to doing: CreateExtension("vector")
        VectorExtension()
    ]
