# Generated by Django 5.0.3 on 2024-04-06 15:54

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_enable_pgvector_extension_20240401_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.VectorField(dimensions=1024)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='recipes.recipe')),
            ],
            options={
                'indexes': [pgvector.django.IvfflatIndex(fields=['embedding'], lists=10, name='recipe_embeddings_ivf', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
