# Generated by Django 5.0.3 on 2024-04-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_recipeembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='origin_url',
            field=models.URLField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='other_source',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yields_type',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('other_source__exact', ''), _negated=True), name='other_source not empty'),
        ),
    ]
