# Generated by Django 5.0.3 on 2024-04-06 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_alter_recipe_origin_url_alter_recipe_other_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='base_amount',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
