# Generated by Django 5.0.3 on 2024-05-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_recipeingredient_base_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='group_name not empty',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yields_type',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
